spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: subscription-manager
          uri: lb://subscription-manager
          predicates:
            - Path=/api/subscriptions/**
          filters:
            - StripPrefix=0
        - id: create-subscription-service
          uri: lb://create-subscription-service
          predicates:
            - Path=/api/subscriptions/**
            - Method=POST
          filters:
            - StripPrefix=0
        - id: eureka-dashboard
          uri: lb://eureka-server
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway 